<img src="numpy-logo.svg" alt="NumPy Logo" style="width: 300px; height: 200px;">
<h1>Creating NumPy Arrays</h1>


In [173]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [175]:
np.__version__

'1.26.4'

<h3>Creating an Array:</h3>

<h4>1. Using array() function: </h4>

In [179]:
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
my_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

<h4>2. Using arange() function:</h4>

In [182]:
my_array = np.arange(1, 11)
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [184]:
my_array = np.arange(1, 11, 2)
my_array

array([1, 3, 5, 7, 9])

<h4>3. Using eye() function:</h4>

In [187]:
my_array = np.eye(6)
my_array

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [189]:
my_array = np.eye(4, dtype=int)
my_array

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

<h4>4. Using zeros() function:</h4>

In [192]:
my_array = np.zeros((5, 3))
my_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [194]:
my_array = np.zeros((5, 3), dtype = int)
my_array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<h4>5. Using ones() function:</h4>

In [197]:
my_array = np.ones((3, 4))
my_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [199]:
my_array = np.ones((3, 4), dtype = int)
my_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

<h4>6. Using full() function:</h4>

In [202]:
my_array = np.full((5, 6), 678.0)
my_array

array([[678., 678., 678., 678., 678., 678.],
       [678., 678., 678., 678., 678., 678.],
       [678., 678., 678., 678., 678., 678.],
       [678., 678., 678., 678., 678., 678.],
       [678., 678., 678., 678., 678., 678.]])

In [204]:
my_array = np.full((5, 6), 678, dtype = float)
my_array

array([[678., 678., 678., 678., 678., 678.],
       [678., 678., 678., 678., 678., 678.],
       [678., 678., 678., 678., 678., 678.],
       [678., 678., 678., 678., 678., 678.],
       [678., 678., 678., 678., 678., 678.]])

<h4>7. Using diag() function:</h4>

In [207]:
my_array = np.diag([1, 2, 3, 4, 5])
my_array

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [209]:
my_list = [1, 2, 3, 4, 5]
my_array = np.diag(my_list)
my_array

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

<h3>Dimensions of an Array :</h3>

In [212]:
my_array = np.array([1, 2, 3, 4, 5, "1"])
my_array

array(['1', '2', '3', '4', '5', '1'], dtype='<U11')

In [217]:
# No dimension
my_array1 = np.array(10)
my_array1

array(10)

In [219]:
# One dimension
my_array2 = np.array([1,2,3,4])
my_array2

array([1, 2, 3, 4])

In [221]:
# Two dimension
my_array3 = np.array([[1,2,3,4],[5,6,7,8]])
my_array3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [223]:
# Three dimension
my_array4 =np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
my_array4

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [225]:
print(f"dimension of my_array1: {my_array1.ndim}")
print(f"dimension of my_array2: {my_array2.ndim}")
print(f"dimension of my_array3: {my_array3.ndim}")
print(f"dimension of my_array4: {my_array4.ndim}")

dimension of my_array1: 0
dimension of my_array2: 1
dimension of my_array3: 2
dimension of my_array4: 3


In [227]:
print(my_array1)
print(f"shape of my_array1: {my_array1.shape} --> mens no dimension")
print()
print(my_array2)
print(f"shape of my_array2: {my_array2.shape} --> mens 1 dimension")
print()
print(my_array3)
print(f"shape of my_array3: {my_array3.shape} --> mens 2 dimension")
print()
print(my_array4)
print(f"shape of my_array4: {my_array4.shape} --> mens 3 dimension")


10
shape of my_array1: () --> mens no dimension

[1 2 3 4]
shape of my_array2: (4,) --> mens 1 dimension

[[1 2 3 4]
 [5 6 7 8]]
shape of my_array3: (2, 4) --> mens 2 dimension

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
shape of my_array4: (2, 2, 4) --> mens 3 dimension


In [229]:
print(f"The data stored in my_array1: {my_array1.dtype}")
print(f"The data stored in my_array2: {my_array2.dtype}")
print(f"The data stored in my_array3: {my_array3.dtype}")
print(f"The data stored in my_array4: {my_array4.dtype}")

The data stored in my_array1: int32
The data stored in my_array2: int32
The data stored in my_array3: int32
The data stored in my_array4: int32


In [231]:
print(f"The data type of my_array1: {type(my_array1)}")
print(f"The data type of my_array2: {type(my_array2)}")
print(f"The data type of my_array3: {type(my_array3)}")
print(f"The data type of my_array4: {type(my_array4)}")

The data type of my_array1: <class 'numpy.ndarray'>
The data type of my_array2: <class 'numpy.ndarray'>
The data type of my_array3: <class 'numpy.ndarray'>
The data type of my_array4: <class 'numpy.ndarray'>


In [233]:
# print(f"The length of my_array1: {len(my_array1)}")
# Output: TypeError: len() of unsized object

print(f"The length of my_array2: {len(my_array2)}")
print(f"The length of my_array3: {len(my_array3)}")
print(f"The length of my_array4: {len(my_array4)}")

The length of my_array2: 4
The length of my_array3: 2
The length of my_array4: 2


<h3>Reshaping the NumPy Array:</h3>

In [236]:
array_1 = np.arange(1, 17)
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [238]:
array_2 = array_1.reshape(2, 8)
array_2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [240]:
array_3 = array_2.reshape(2, 2, 4)
array_3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [242]:
# array_4 = array_3.reshape(15,)
# array_4
# Output : ValueError: cannot reshape array of size 16 into shape (15,)

In [244]:
array_4 = array_3.reshape(16,)
array_4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

<h3>Reshaping Multi-dimensional Array to One-dimensional Array:</h3>

<h4>1. Using reshape() function:</h4>

In [248]:
array_1 = np.array([[1, 2, 3], [4, 5, 6]])
array_2 = array_1.reshape(-1) # 1D
print(array_1)
print(array_2)
print()

array_1[0, 1] = 99
array_2[3] = 88

print(array_1)
print(array_2)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

[[ 1 99  3]
 [88  5  6]]
[ 1 99  3 88  5  6]


In [250]:
array_3 = array_1.reshape(1, -1) # 2D
print(array_3)

[[ 1 99  3 88  5  6]]


In [252]:
print(f"reshape() method: {np.may_share_memory(array_1, array_2)}")

reshape() method: True


<h4>2. Using ravel() function:</h4>

In [255]:
array_1 = np.array([[1, 2, 3], [4, 5, 6]])
array_2 = array_1.ravel()
print(array_1)
print(array_2)
print()

array_1[0, 1] = 99
array_2[3] = 88

print(array_1)
print(array_2)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

[[ 1 99  3]
 [88  5  6]]
[ 1 99  3 88  5  6]


In [257]:
print(f"ravel() method: {np.may_share_memory(array_1, array_2)}")

ravel() method: True


<h4>3. Using flatten() function:</h4>

In [260]:
array_1 = np.array([[1, 2, 3], [4, 5, 6]])
array_2 = array_1.flatten()
print(array_1)
print(array_2)
print()

array_1[0, 1] = 99

print(array_1)
print(array_2)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

[[ 1 99  3]
 [ 4  5  6]]
[1 2 3 4 5 6]


In [262]:
print(f"flatten() method: {np.may_share_memory(array_1, array_2)}")

flatten() method: False
