<img src="numpy-logo.svg" alt="NumPy Logo" style="width: 300px; height: 200px;">
<h1>Indexing and Slicing NumPy Arrays</h1>

In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

<h3>Numpy Array Indexing:</h3>

<h4>1. One Dimension</h4>

In [52]:
my_array1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print(my_array1)
print(len(my_array1))

[10 20 30 40 50 60 70 80 90]
9


In [54]:
# positive indexing
print(my_array1[0])
print(my_array1[8])

10
90


In [56]:
# negative indexing
print(my_array1[-1])
print(my_array1[-9])

90
10


<h4>2. Two Dimension</h4>

In [59]:
my_array2 = np.array([[10, 20, 30, 40], [50, 60, 70, 0], [90, 50, 80, 70]])
my_array2

array([[10, 20, 30, 40],
       [50, 60, 70,  0],
       [90, 50, 80, 70]])

In [61]:
# positive indexing
print(my_array2[0, 2])
print(my_array2[2, 2])
print(my_array2[1, 2])
print(my_array2[1, 3])
print(my_array2[0])

30
80
70
0
[10 20 30 40]


In [63]:
# negative indexing
print(my_array2)
print(my_array2[-1, -2])
print(my_array2[-2, -3])
print(my_array2[-1])

[[10 20 30 40]
 [50 60 70  0]
 [90 50 80 70]]
80
60
[90 50 80 70]


<h4>3. Three Dimension</h4>

In [66]:
my_array3 = np.array([[[10, 20, 30], [40, 50, 60]], [[70, 80, 90], [50, 80, 70]]])
my_array3

array([[[10, 20, 30],
        [40, 50, 60]],

       [[70, 80, 90],
        [50, 80, 70]]])

In [68]:
# positive indexing
print(my_array3[0])
print(my_array3[0, 1])
print(my_array3[0, 1, 2])
print(my_array3[0] [1] [2])
print(my_array3[[0], [1], [2]])

[[10 20 30]
 [40 50 60]]
[40 50 60]
60
60
[60]


In [70]:
# negative indexing
print(my_array3[-1])
print(my_array3[-1, -1])
print(my_array3[-1, -1, -1])
print(my_array3[-1][-1][-2])
print(my_array3[[-1], [-1], [-2]])

[[70 80 90]
 [50 80 70]]
[50 80 70]
70
80
[80]


<h3>Numpy Array Slicing:</h3>

<h4>1. One Dimension</h4>

In [74]:
print(f"One Dimensional Array:\n")
print(my_array1, "\n")

print(f"Positive Slicing:\n")
print(my_array1[:], "\n")
print(my_array1[::], "\n")
print(my_array1[::2], "\n")
print(my_array1[1], "\n")
print(my_array1[1:4], "\n")
print(my_array1[1:5:2], "\n")
print(my_array1[4:], "\n")
print(my_array1[:4], "\n")

One Dimensional Array:

[10 20 30 40 50 60 70 80 90] 

Positive Slicing:

[10 20 30 40 50 60 70 80 90] 

[10 20 30 40 50 60 70 80 90] 

[10 30 50 70 90] 

20 

[20 30 40] 

[20 40] 

[50 60 70 80 90] 

[10 20 30 40] 



In [76]:
print(f"Negative Slicing:\n")
print(my_array1[::-2], "\n")
print(my_array1[-1], "\n")
print(my_array1[-1:-4:-1], "\n")
print(my_array1[-1:-5:-2], "\n")
print(my_array1[-4:], "\n")
print(my_array1[:-4], "\n")

Negative Slicing:

[90 70 50 30 10] 

90 

[90 80 70] 

[90 70] 

[60 70 80 90] 

[10 20 30 40 50] 



<h4>2. Two Dimension</h4>

In [79]:
print(f"Two Dimensional Array:\n")
print(my_array2,"\n")

print(f"Positive and Negative Slicing:\n")
print(my_array2[0, 0:2], "\n")
print(my_array2[1,], "\n")
print(my_array2[1, :], "\n")
print(my_array2[:, 1], "\n")
print(my_array2[1:3], "\n")
print(my_array2[:, 1:3], "\n")
print(my_array2[1:3, 1], "\n")
print(my_array2[1:3, :1], "\n")
print(my_array2[:-1, :-1], "\n")

Two Dimensional Array:

[[10 20 30 40]
 [50 60 70  0]
 [90 50 80 70]] 

Positive and Negative Slicing:

[10 20] 

[50 60 70  0] 

[50 60 70  0] 

[20 60 50] 

[[50 60 70  0]
 [90 50 80 70]] 

[[20 30]
 [60 70]
 [50 80]] 

[60 50] 

[[50]
 [90]] 

[[10 20 30]
 [50 60 70]] 



<h4>3. Three Dimension</h4>

In [85]:
print(f"The Dimensional Array:\n")
print(my_array3,"\n")

print(f"Positive and Negative Slicing:\n")
print(my_array3[0: 2], "\n")
print(my_array3[0:1, 0:2], "\n")
print(my_array3[0:1, 0:2, 0:2], "\n")

print(my_array3[:, -1, -1], "\n")
print(my_array3[-1, :, -1], "\n")
print(my_array3[-1, -1, :], "\n")

The Dimensional Array:

[[[10 20 30]
  [40 50 60]]

 [[70 80 90]
  [50 80 70]]] 

Positive and Negative Slicing:

[[[10 20 30]
  [40 50 60]]

 [[70 80 90]
  [50 80 70]]] 

[[[10 20 30]
  [40 50 60]]] 

[[[10 20]
  [40 50]]] 

[60 70] 

[90 70] 

[50 80 70] 

