<img src="numpy-logo.svg" alt="NumPy Logo" style="width: 300px; height: 200px;">
<h1>Applying Conditions on NumPy Arrays</h1>

In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

<h4>Create a Reference :</h4>

In [16]:
x1 = np.arange(11)
x1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
x2 = x1

print(x1)
print(x2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [20]:
x2[0] = 10

print(x1)
print(x2)

[10  1  2  3  4  5  6  7  8  9 10]
[10  1  2  3  4  5  6  7  8  9 10]


In [22]:
x1[2] = 30

print(x1)
print(x2)

[10  1 30  3  4  5  6  7  8  9 10]
[10  1 30  3  4  5  6  7  8  9 10]


In [24]:
print(np.shares_memory(x1, x2))

print(id(x1))
print(id(x2))

True
2363919474896
2363919474896


<h4>Create a View :</h4>

In [27]:
y1 = np.arange(11)
y1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
y2 = y1.view()

print(y1)
print(y2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [31]:
y1[0] = 10
y2[3] = 20

print(y1)
print(y2)

[10  1  2 20  4  5  6  7  8  9 10]
[10  1  2 20  4  5  6  7  8  9 10]


In [33]:
print(np.shares_memory(y1, y2))

print(id(y1))
print(id(y2))

True
2363919474992
2363932801904


<h4>Create a Copy :</h4>

In [36]:
z1 = np.arange(11)
z1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
z2 = np.copy(z1) # or z2 = z1. copy()

print(z1)
print(z2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [40]:
z1[0] = 10
z2[3] = 20

print(z1)
print(z2)

[10  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 20  4  5  6  7  8  9 10]


In [42]:
print(np.shares_memory(z1, z2))

print(id(z1))
print(id(z2))

False
2363932801616
2363932802192


<h4>Applying Conditions :</h4>

In [45]:
a1 = np.array([[1, 2, 2], [4, 5, 6]])
print(a1)

a2 = np.array([[3, 2, 3], [4, 5, 6]])
a2

[[1 2 2]
 [4 5 6]]


array([[3, 2, 3],
       [4, 5, 6]])

In [47]:
a1 >= 3

array([[False, False, False],
       [ True,  True,  True]])

In [49]:
a1[a1 >= 3]

array([4, 5, 6])

In [51]:
(a1 >= 3) & (a1 <= 5)

array([[False, False, False],
       [ True,  True, False]])

In [53]:
a1[(a1 >= 3) & (a1 <= 5)]

array([4, 5])

In [55]:
a1 == a2

array([[False,  True, False],
       [ True,  True,  True]])

In [57]:
a1[a1 == a2]

array([2, 4, 5, 6])

<h4>Transposing an Array :</h4>

In [60]:
a1 = np.array([[1, 2, 2], [4, 5, 6]])
print(a1)

[[1 2 2]
 [4 5 6]]


In [62]:
print(np.transpose(a1))
print()
print(a1.transpose())
print()
print(a1.T)
print()
print(a1)

[[1 4]
 [2 5]
 [2 6]]

[[1 4]
 [2 5]
 [2 6]]

[[1 4]
 [2 5]
 [2 6]]

[[1 2 2]
 [4 5 6]]


In [66]:
c1 = np.array([[[1, 2, 2], [4, 5, 6]], [[1, 2, 2], [4, 5, 6]]])
print(c1)

[[[1 2 2]
  [4 5 6]]

 [[1 2 2]
  [4 5 6]]]


In [68]:
c1.transpose()

array([[[1, 1],
        [4, 4]],

       [[2, 2],
        [5, 5]],

       [[2, 2],
        [6, 6]]])

<h4>Stacking :</h4>

In [71]:
a1 = np.array([[1, 2, 2], [4, 5, 6]])
a1

array([[1, 2, 2],
       [4, 5, 6]])

In [73]:
b1 = np.hstack(a1)
b1

array([1, 2, 2, 4, 5, 6])

In [75]:
b2 = np.vstack(a1)
b2

array([[1, 2, 2],
       [4, 5, 6]])

In [77]:
b3 = np.vstack(b1)
b3

array([[1],
       [2],
       [2],
       [4],
       [5],
       [6]])

<h4>Insert and Delete :</h4>

In [84]:
aa = np.arange(10)
print(aa)
print()

bb = np.array([[1, 2, 2], [4, 5, 6]])
print(bb)
print()

cc = np.insert(bb, 2, aa)
print(cc)

[0 1 2 3 4 5 6 7 8 9]

[[1 2 2]
 [4 5 6]]

[1 2 0 1 2 3 4 5 6 7 8 9 2 4 5 6]


<h4>np.delete(arr, obj, axis = None)</h4>
<h6>arr --> array to delete element from</h6>
<h6>obj --> indices at which values are deleted</h6>
<h6>axis --> by default flattend array (axis = 0)</h6>
<h6>axis = 0 (rows)</h6>
<h6>axis = 1 (columns)</h6>

In [87]:
a1 = np.arange(10)
print(a1)

a2 = np.delete(a1, 2)
print(a2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 3 4 5 6 7 8 9]


In [89]:
b1 = np.arange(10)
print(b1)

indices = [1,2]
b2 = np.delete(b1, obj = indices, axis = 0)
print(b2)

[0 1 2 3 4 5 6 7 8 9]
[0 3 4 5 6 7 8 9]


In [91]:
c1 = np.array([[1, 2, 2], [4, 5, 6]])
print(c1)

c2 = np.delete(c1, [1,1], axis = 1)
print(c2)

[[1 2 2]
 [4 5 6]]
[[1 2]
 [4 6]]


<h4>Serching Arrays :</h4> 

In [94]:
dd1 = np.array([1, 2, 2, 4, 5, 6, 3, 4, 1, 5, 6, 7])
print(dd1)

[1 2 2 4 5 6 3 4 1 5 6 7]


In [96]:
np.where(dd1 > 3)

(array([ 3,  4,  5,  7,  9, 10, 11], dtype=int64),)

In [98]:
np.where(dd1 == 2)

(array([1, 2], dtype=int64),)

In [100]:
np.where(dd1 % 2 == 0)

(array([ 1,  2,  3,  5,  7, 10], dtype=int64),)

In [102]:
np.where(dd1 > 2, dd1 , 0)

array([0, 0, 0, 4, 5, 6, 3, 4, 0, 5, 6, 7])

In [104]:
print(dir(list))
print()
print(dir(dd1))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlp

<h4>Mathematical Operations : </h4>

In [107]:
mm = np.array([[1, 2, 2], [4, 5, 6]])
mm

array([[1, 2, 2],
       [4, 5, 6]])

In [109]:
np.sin(mm)

array([[ 0.84147098,  0.90929743,  0.90929743],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [111]:
np.cos(mm)

array([[ 0.54030231, -0.41614684, -0.41614684],
       [-0.65364362,  0.28366219,  0.96017029]])

In [113]:
(np.sin(mm))/(np.cos(mm))

array([[ 1.55740772, -2.18503986, -2.18503986],
       [ 1.15782128, -3.38051501, -0.29100619]])

In [115]:
np.exp(mm)

array([[  2.71828183,   7.3890561 ,   7.3890561 ],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [117]:
np.sum(mm)

20

In [119]:
np.sum(mm, axis = 0)

array([5, 7, 8])

In [121]:
np.sum(mm,axis = 1)

array([ 5, 15])

<h4>Mean : The Average Value (SUM / COUNT) </h4>

In [124]:
np.mean(mm)

3.3333333333333335

<h4>Median : The Middle Value</h4>
<h5>Steps:</h5>
<h6>1. Ascending Order</h6>
<h6>2. Pick Middle Number</h6>
<h6>3. If there are two middle numbers, add them and divide by two</h6>

In [127]:
np.median(mm)

3.0

<h4>Mode : The Most Frequent Value</h4>
<h5>Special Cases:</h5>
<h6>1. No mode if all the numbers occur the same amount of times</h6>
<h6>2. More than one mode if more than one number is the most</h6>

In [130]:
from scipy import stats
stats.mode(mm)

ModeResult(mode=array([1, 2, 2], dtype=int64), count=array([1, 1, 1], dtype=int64))

<h4>Range: Diffence between Highest and Lowest Numbers</h4>
<h5>Steps: </h5>
<h6>1. Ascending Order</h6>
<h6>2. Range = Max Value - Min Value</h6>


In [132]:
np.max(mm) - np.min(mm)

5